### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by uaex** [daemooon/Clash-for-iOS#10]
订阅URL后, 不能选择节点? 🤔
还有就是点击连接后闪断, 没有看到日志, 想用Xcode调试发现插件并没有运行

**Comment by daemooon** [comment]
> 订阅URL后, 不能选择节点? 🤔
> 还有就是点击连接后闪断, 没有看到日志, 想用Xcode调试发现插件并没有运行

应该是没有Country.mmdb数据库，去设置里下载或者导入之后再连接吧！

**Comment by uaex** [comment]
GeoIP数据库添加了的

**Comment by daemooon** [comment]
> GeoIP数据库添加了的

```swift
    static func set(current config: String) throws {
        var err: NSError?
        guard !ClashSetConfig(config, &err), let err = err else {
            return
        }
        throw err
    }
```
把这个方法里面的实现注释掉试一下。
1、确定配置文件是没问题的。如果有问题可能导致panic。
2、Debug一下PacketTunnel进程，应该可以看到crash在什么位置。

**Comment by uaex** [comment]
测试用的插件ID 没使用 PacketTunnel 这个名字

**Comment by uaex** [comment]
VPN显示已连接, 选择了代理. 不过还是无法访问google 🤔

**Comment by daemooon** [comment]
> VPN显示已连接, 选择了代理. 不过还是无法访问google 🤔

取消注释上面的代码，连接，查看策略组，是否正常显示。如果为空，或者无法连接，检查配置文件，因为使用的是 clash 开源内核，有些特性是不支持的。

如果正常，设置日志等级未调试，连接 mac 控制台，查看 PacketTunnel 进程日志。

**Comment by uaex** [comment]
> > VPN显示已连接, 选择了代理. 不过还是无法访问google 🤔
> 
> 取消注释上面的代码，连接，查看策略组，是否正常显示。如果为空，或者无法连接，检查配置文件，因为使用的是 clash 开源内核，有些特性是不支持的。
> 
> 如果正常，设置日志等级未调试，连接 mac 控制台，查看 PacketTunnel 进程日志。

都配置了, 日志等级为 调试, 策略组也有. 我在macOS 上使用的是一样的订阅, 使用正常.

**Comment by uaex** [comment]
有好几个	got event: Connection invalid

**Comment by daemooon** [comment]
> 有好几个 got event: Connection invalid

这个我还不知道是怎么回事，应该集成lwip之后出现的。

**Comment by daemooon** [comment]
> 成功了, 我注册了PacketTunnel的插件BundleID, 就正常了. 不知道是不是有其他地方还强制要求了 PacketTunnel的后缀名.
> 另外每次连接后策略组的Proxy就自动变成Auto了.

应该没有了，我看看之后把这个也放到Config里面吧！

每次变Auto，因为全局禁用了store-selected。即使你配置文件里设置了true也会被覆盖到，你可以修改这里试试。
```swift
static func run() throws {
    let config = """
    mixed-port: 8080
    mode: \(tunnelMode.rawValue)
    log-level: \(logLevel.rawValue)
    rules:
        - MATCH,DIRECT
    """
```

**Comment by uaex** [comment]
> ```swift
> static func run() throws {
> ```

好的, 十分感谢!

**Comment by daemooon** [comment]
> ```swift
> ```swift
> static func run() throws {
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> 好的, 十分感谢!
> ```

如果实现新的功能，欢迎合并回 Clash for iOS
