### ISSUE TITLE
请求增加framework接口

### ISSUE THREAD

**Issue by nicknull** [daemooon/Clash-for-iOS#11]
作者你好
可否给出  策略组信息、代理信息、规则 信息、订阅相关的流量信息和账户信息 相关的接口
目前framework没有找到相关接口

**Comment by nicknull** [comment]
或者有什么其他方式参与代码贡献

**Comment by daemooon** [comment]
> 作者你好
> 可否给出 策略组信息、代理信息、规则 信息、订阅相关的流量信息和账户信息 相关的接口
> 目前framework没有找到相关接口

```objc
// 策略组信息、代理信息
FOUNDATION_EXPORT NSData* _Nullable ClashGetProxies(void);

// 流量信息
@protocol ClashClient <NSObject>
- (void)onTraffic:(int64_t)up down:(int64_t)down;
@end

FOUNDATION_EXPORT NSData* _Nullable ClashSnapshot(void);
```

规则目前没加。

账户信息是什么？？？

**Comment by nicknull** [comment]
就是订阅用户的流量额度和已用  用户订阅到期时间 这些信息 
clash for windows中有实现此部分功能 不知道这部分是否属于 clash内核中实现的

**Comment by daemooon** [comment]
> 就是订阅用户的流量额度和已用 用户订阅到期时间 这些信息
> clash for windows中有实现此部分功能 不知道这部分是否属于 clash内核中实现的

订阅管理不在clash内核实现

**Comment by nicknull** [comment]
> > 就是订阅用户的流量额度和已用 用户订阅到期时间 这些信息
> > clash for windows中有实现此部分功能 不知道这部分是否属于 clash内核中实现的
> 
> 订阅管理不在clash内核实现

感谢您的回复
