### ISSUE TITLE
ClashKit Implementation

### ISSUE THREAD

**Issue by EbrahimTahernejad** [daemooon/Clash-for-iOS#13]
Thank you for your work

Is it possible for you to share your tun implementation? I'm trying to create something like ClashKit for other forks of the clash repo, some of them have experimental but useful methods to combat IRAN's firewall.

How did you fix the RAM issue in iOS? for me, I can't go lower than 20MB

**Comment by daemooon** [comment]
> Thank you for your work
> 
> Is it possible for you to share your tun implementation? I'm trying to create something like ClashKit for other forks of the clash repo, some of them have experimental but useful methods to combat IRAN's firewall.
> 
> How did you fix the RAM issue in iOS? for me, I can't go lower than 20MB

Unfortunately, I am unable to reduce RAM usage to below 20M. I apologize that I cannot currently share the code for ClashKit, as it is too raw and ugly. However, I can share with you the tun mode implemented using gvisor's network stack, based on [this](https://github.com/yaling888/clash)  project

**Comment by daemooon** [comment]
If you are familiar with the C language, you can try to port [this](https://github.com/heiher/hev-socks5-tunnel)  project to iOS, and I believe it will have good results.

**Comment by EbrahimTahernejad** [comment]
> > Thank you for your work
> > Is it possible for you to share your tun implementation? I'm trying to create something like ClashKit for other forks of the clash repo, some of them have experimental but useful methods to combat IRAN's firewall.
> > How did you fix the RAM issue in iOS? for me, I can't go lower than 20MB
> 
> Unfortunately, I am unable to reduce RAM usage to below 20M. I apologize that I cannot currently share the code for ClashKit, as it is too raw and ugly. However, I can share with you the tun mode implemented using gvisor's network stack, based on [this](https://github.com/yaling888/clash) project

I understand, although, I would've been fine with ugly code as well. I respect your choice though.
I don't know much about go. I've just started learning about these things as my country has implemented something like china's firewall recently.

**Comment by EbrahimTahernejad** [comment]
> If you are familiar with the C language, you can try to port [this](https://github.com/heiher/hev-socks5-tunnel) project to iOS, and I believe it will have good results.

I've made some progress with this one. I'll post it on my github if I can do anything useful with it.

**Comment by daemooon** [comment]
> > > Thank you for your work
> > > Is it possible for you to share your tun implementation? I'm trying to create something like ClashKit for other forks of the clash repo, some of them have experimental but useful methods to combat IRAN's firewall.
> > > How did you fix the RAM issue in iOS? for me, I can't go lower than 20MB
> > 
> > 
> > Unfortunately, I am unable to reduce RAM usage to below 20M. I apologize that I cannot currently share the code for ClashKit, as it is too raw and ugly. However, I can share with you the tun mode implemented using gvisor's network stack, based on [this](https://github.com/yaling888/clash) project
> 
> I understand, although, I would've been fine with ugly code as well. I respect your choice though. I don't know much about go. I've just started learning about these things as my country has implemented something like china's firewall recently.

I have sent you a collaboration invitation.

**Comment by EbrahimTahernejad** [comment]
> > > > Thank you for your work
> > > > Is it possible for you to share your tun implementation? I'm trying to create something like ClashKit for other forks of the clash repo, some of them have experimental but useful methods to combat IRAN's firewall.
> > > > How did you fix the RAM issue in iOS? for me, I can't go lower than 20MB
> > > 
> > > 
> > > Unfortunately, I am unable to reduce RAM usage to below 20M. I apologize that I cannot currently share the code for ClashKit, as it is too raw and ugly. However, I can share with you the tun mode implemented using gvisor's network stack, based on [this](https://github.com/yaling888/clash) project
> > 
> > 
> > I understand, although, I would've been fine with ugly code as well. I respect your choice though. I don't know much about go. I've just started learning about these things as my country has implemented something like china's firewall recently.
> 
> I have sent you a collaboration invitation.

thank you 

> > > > Thank you for your work
> > > > Is it possible for you to share your tun implementation? I'm trying to create something like ClashKit for other forks of the clash repo, some of them have experimental but useful methods to combat IRAN's firewall.
> > > > How did you fix the RAM issue in iOS? for me, I can't go lower than 20MB
> > > 
> > > 
> > > Unfortunately, I am unable to reduce RAM usage to below 20M. I apologize that I cannot currently share the code for ClashKit, as it is too raw and ugly. However, I can share with you the tun mode implemented using gvisor's network stack, based on [this](https://github.com/yaling888/clash) project
> > 
> > 
> > I understand, although, I would've been fine with ugly code as well. I respect your choice though. I don't know much about go. I've just started learning about these things as my country has implemented something like china's firewall recently.
> 
> I have sent you a collaboration invitation.

thank you :) <3

**Comment by LeeCenY** [comment]
> > Thank you for your work
> > Is it possible for you to share your tun implementation? I'm trying to create something like ClashKit for other forks of the clash repo, some of them have experimental but useful methods to combat IRAN's firewall.
> > How did you fix the RAM issue in iOS? for me, I can't go lower than 20MB
> 
> Unfortunately, I am unable to reduce RAM usage to below 20M. I apologize that I cannot currently share the code for ClashKit, as it is too raw and ugly. However, I can share with you the tun mode implemented using gvisor's network stack, based on [this](https://github.com/yaling888/clash) project

May I ask if I can be invited to this one too?
