### ISSUE TITLE
您好，优质节点，但是上传下载速度慢

### ISSUE THREAD

**Issue by niufuwei** [daemooon/Clash-for-iOS#15]
您好，优质节点，但是上传下载速度慢，YouTube刚开始加载图片很快，播放视频等好久缓冲，大概几十秒之后，看其他视频都是秒开，速度刚刚的，是怎么回事呢？在tg上，上传视频也是几十kb这样子，和节点有关系吗？还是配置上的问题

**Comment by niufuwei** [comment]
图片之类的资源加载都很快，唯独视频的上传下载都慢得很

**Comment by niufuwei** [comment]
同样的节点，我导入shadowsocks，速度杠杠的，看YouTube几乎没有任何缓冲，秒开。

**Comment by niufuwei** [comment]
是咱们哪里配置的问题吗

**Comment by daemooon** [comment]
应该是 tun 的实现问题😳

**Comment by niufuwei** [comment]
有大概定位吗？我去找找看，我对tun那块的技术不太熟悉，😳

**Comment by daemooon** [comment]
> 有大概定位吗？我去找找看，我对tun那块的技术不太熟悉，😳

一起研究一下[这个](https://github.com/heiher/hev-socks5-tunnel) 项目？我想把它移植到项目里。

**Comment by niufuwei** [comment]
好的，我也研究下。您这边如果解决了，麻烦说下。谢谢哈
