### ISSUE TITLE
昨天那个看视频慢的，找到了一个处理办法

### ISSUE THREAD

**Issue by niufuwei** [daemooon/Clash-for-iOS#16]
我使用的mojie的订阅url
我查看了一下配置文件，其中有一个    - 'DOMAIN-SUFFIX,youtu.be,谷歌服务'

如果不让他自动选择节点，而是去找到谷歌服务列表，选择其中有一个直连

就速度杠杠的，看YouTube视频。和小火箭不相上下。

所以，是不是在配置上可以把这个问题解决掉？

**Comment by daemooon** [comment]
“ 如果不让他自动选择节点，而是去找到谷歌服务列表，选择其中有一个直连”

这一段没太看懂。你的期望是如果匹配到 youtu.be，让 clash 在谷歌服务的节点列表里面选择一个节点出站么？我这么理解对么？

**Comment by daemooon** [comment]
还是说，你认为谷歌服务列表里部分节点延迟低，但是上传下载速度不佳，需要手动选择一个而不是让 clash 自己依据延迟速度来选？

**Comment by daemooon** [comment]
@niufuwei
