### ISSUE TITLE
will it work with socks5

### ISSUE THREAD

**Issue by tozik** [daemooon/Clash-for-iOS#9]
Hi, greatest sample.
but I can't understand will it work with socks5 (server through tun 2 socks)?

**Comment by AleksTozik** [comment]
i also found in your repo
Tun2SocksKit, but not able to run them, could you add some notes please, looks like it without header

**Comment by daemooon** [comment]
> Hi, greatest sample.
> but I can't understand will it work with socks5 (server through tun 2 socks)?

Implement tun mode like Clash.Meta: https://github.com/MetaCubeX/Clash.Meta

**Comment by daemooon** [comment]
> i also found in your repo
> Tun2SocksKit, but not able to run them, could you add some notes please, looks like it without header

See release 1.2.0 PacketTunnel/Tun2Socks.swift

**Comment by tozik** [comment]
> > i also found in your repo
> 
> > Tun2SocksKit, but not able to run them, could you add some notes please, looks like it without header
> 
> 
> 
> See release 1.2.0 PacketTunnel/Tun2Socks.swift

They are have just static library , without headers, could you send them?

**Comment by daemooon** [comment]
> > > i also found in your repo
> > 
> > 
> > > Tun2SocksKit, but not able to run them, could you add some notes please, looks like it without header
> > 
> > 
> > See release 1.2.0 PacketTunnel/Tun2Socks.swift
> 
> They are have just static library , without headers, could you send them?

Using @_sligen_name
